name: KmerLingo
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
   # Pour lire des fichiers audio
  audioplayers: ^6.5.1  
  fl_chart: ^0.69.0
  rive: ^0.13.0

  flutter_staggered_animations: ^1.1.1
  # Pour enregistrer/traiter du son
  flutter_sound: ^9.2.13  
  

  # Pour accéder aux chemins du stockage local
  path_provider: ^2.0.16  

  # Pour demander les permissions (micro, stockage, etc.)
  permission_handler: ^11.3.1  

  


  cupertino_icons: ^1.0.8
  http: ^1.5.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  lottie: ^2.2.0


flutter:

  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/Loading_animation.json
    - assets/favorites.json
    - assets/animal.riv

